version: '3'

services:
  bot_api:
    build: .
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/app
  mysql:
    image: mysql
    restart: always
    ports:
      - '3366:3306'
    environment:
      MYSQL_ROOT_PASSWORD: vnd
      MYSQL_DATABASE: bot_db
