version: '3'

services:
  mysql:
    image: mysql
    restart: always
    ports:
      - '3366:3306'
    environment:
      MYSQL_ROOT_PASSWORD: vnd
      MYSQL_DATABASE: bot_db
    networks:
      - mynetwork

networks:
  mynetwork:
